### ISSUE TITLE
Wie installiere ich das Plugin?

### ISSUE THREAD

**Issue by olien** [gn2netwerk/gn2_shutdown_filter_google_webfonts#3]
ich lade das hier hoch:

![image](https://user-images.githubusercontent.com/330516/200176718-f1a3a485-9746-4054-82c1-ec63395f4e5b.png)

das kommt:

![image](https://user-images.githubusercontent.com/330516/200176663-a7b96c29-5192-46bb-be3d-31712feea60e.png)

(Wordpress frisch aktualisiert)

**Comment by IngoWinter** [comment]
Zieh dir bitte das neueste Release und probiere es damit nochmal - sollte nun funktionieren.

**Comment by olien** [comment]
Jetzt geht es. danke. (Löst aber leider nicht mein Problem)

![image](https://user-images.githubusercontent.com/330516/200293862-0c6434fd-3277-4006-bcaa-49cb20237706.png)
